name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    timeout-minutes: 10

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.6.0

      - name: install dependencies
        run: dart pub get

      - name: Validate
        run: dart run devtools_extensions validate --package=.

      - name: Build and Copy
        run: dart run devtools_extensions build_and_copy --source=. --dest=./extension/devtools

      - name: Publish
        run: dart pub publish --force
