name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish_release:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: kuhnroyal/flutter-fvm-config-action@v3
        id: fvm-config-action

      - uses: subosito/flutter-action@v2.18.0
        with:
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}

      - name: install dependencies
        run: flutter pub get

      - name: Validate
        run: dart run devtools_extensions validate --package=.

      - name: Build and Copy
        run: dart run devtools_extensions build_and_copy --source=. --dest=./extension/devtools

      - name: Publish
        run: dart pub publish
